# dein_lazy.toml
# EOL:LF / code:UTF-8

[[plugins]] # Vimヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # ツリー型エクスプローラー NERDTree
repo = 'preservim/nerdtree'
hook_add = '''
" # プラグイン設定 {
" ## NERDTree
" ## <C-o> open NERDTree
nmap <silent> <C-o> :NERDTreeToggle<CR>
'''

# 曖昧入力でファイルを開く fzf {
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
" ## fzf
if has('win32')
    function g:ExecInBash(command)
        let tmp = &shell
        set shell=bash
        execute a:command
        let &shell = tmp
    endfunction
    nmap <silent> fzf :call ExecInBash('FZF')<CR>
elseif has('unix')
    nmap <silent> fzf :FZF<CR>
endif
'''
# } fzf

[[plugins]] # ユーザー定義コマンドを置き換える vim-altercmd
repo = 'kana/vim-altercmd'
hook_add = '''
call altercmd#load()
AlterCommand lnote Lnote
AlterCommand wnote Wnote
'''
